### ISSUE TITLE
Upgrade to Quasar 2 / Vue 3

### ISSUE THREAD

**Issue by claustres** [kalisio/crisis#393]
**Web app**

* activities
  * [x] organisations
  * [x] members
  * [x] tags
  * [x] groups
  * [x] event templates
  * [x] events 
  * [x] event
  * [x] archived events
  * [x] catalog
  * [x] plan templates
  * [x] plans
  * [x] archived plans
 * [x] tours
* tests
  * [x] backend
  * [x] frontend

* remaining issues
  * [x] Realtime update after adding/removing a tag/group on a member causes an error
    Linked to https://github.com/feathersjs-ecosystem/feathers-reactive/issues/214 and  the fact that we sort according to `profile.name` which is a perspective not retrieved in member objects
 
**Mobile apps**
  * [x] `cordova-plugin-file-opener2` installation fails, see https://github.com/pwlin/cordova-plugin-file-opener2/issues/311
  * [x]  `cordova-plugin-file-opener2` store deployment fails, see https://github.com/pwlin/cordova-plugin-file-opener2/issues/329
  * [x] `cordova-plugin-push` installation fails on iOS
  * [x] ~~iOS notifications do not work anymore~~ => to be replaced as per https://github.com/kalisio/aktnmap/issues/421
